services:
  api-gateway-service:
    build: ./  # Indica la directory dove si trova il Dockerfile
    container_name: api-gateway-service
    ports:
      - "${PORT:-8080}:${SERVER_PORT:-8080}"  # porta dinamica o 8080
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500     
    networks:
      - my-network
networks:
  my-network:
    external:
      name: global-network