apiVersion: apps/v1
kind: Deployment
metadata:
  name: connessioni
  namespace: asw-goodmusic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asw-goodmusic
  template:
    metadata:
      labels:
        app: asw-goodmusic
    spec:
      containers:
        - name: connessioni
          image: thomasfarinelli/connessioni:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://connessioni-db.asw-goodmusic.svc.cluster.local:5432/connessioni"
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "consul.asw-goodmusic.svc.cluster.local:8500"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "8500"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.asw-goodmusic.svc.cluster.local:9092"
