spring: 
  application: 
    name: connessioni
  cloud:
    consul:
      discovery: 
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        queryPassing: true 

  datasource:
    url: jdbc:postgresql://localhost:5432/connessioni
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: asw-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      name: ConnessioniProducer
      channel:
        out1: asw-ConnessioneCreated
        out2: asw-ConnessioneDeleted
      messages-to-send: 20

server:
  port: ${PORT:${SERVER_PORT:0}}
  forward-headers-strategy: framework

spring.jpa.open-in-view: false
