spring: 
  application: 
    name: recensioni
  config:
    activate:
      on-profile: prod
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: 
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        # configurazione per effettuare esprimenti, NON USARE UN PRODUZIONE 
        # dopo quanto tempo consul deve smettere di restituire servizi che non rispondono all'health check? 
        #healthCheckCriticalTimeout: 45s
        # consul deve restituire solo servizi che passano l'health check (default=false) 
        queryPassing: true 

  datasource:
    url: jdbc:postgresql://localhost:5432/recensioni
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  kafka:
    bootstrap-servers: asw-kafka:9092  # Indirizzo del broker Kafka
    # Configurazione per il Producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializzatore per la chiave (String)
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Serializzatore per il valore (Recensione)
      name: Producer
      # Topic a cui inviare i messaggi
      channel:
        out: asw-RecensioniCreatedToFiltro  # Nome del topic a cui inviare i messaggi Kafka
      messages-to-send: 20

spring.jpa.open-in-view: false

server:
  port: ${PORT:${SERVER_PORT:0}}
  forward-headers-strategy: framework
