spring:
  main:
    web-application-type: NONE
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: 
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        # configurazione per effettuare esprimenti, NON USARE UN PRODUZIONE 
        # dopo quanto tempo consul deve smettere di restituire servizi che non rispondono all'health check? 
        #healthCheckCriticalTimeout: 45s
        # consul deve restituire solo servizi che passano l'health check (default=false) 
        queryPassing: true 
  kafka:
    bootstrap-servers: asw-kafka:9092
    consumer:
      group-id: FiltroRecensioniToBrevi
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # Se necessario, abilita i pacchetti di fiducia per la deserializzazione JSON
      # properties:
      #   spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 0
    filter:
      name: RecensioniToRecensioniBrevi
    channel:
      in: asw-RecensioniCreatedToFiltro
      out: asw-FiltroToRecensioniBreve
    groupid: simple-filter

server: 
  port: ${PORT:${SERVER_PORT:0}}